services:
  muxlib:
    build: .
    user: "1234:1365"  # Output of `id -u` and `id -g`
    container_name: muxlib
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${SAVE_FOLDER:-./downloads}:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
      - SAVE_FOLDER=/app/downloads #this env variabile is used first
      - TMP_FOLDER=/app/tmp
